/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fqx_anyplay_service_APController */

#ifndef _Included_com_fqx_anyplay_service_APController
#define _Included_com_fqx_anyplay_service_APController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    PublishEvent
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_PublishEvent
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    native_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_native_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    native_setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_native_1setup
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    AirTunesStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_anyplay_service_APController_AirTunesStart
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    AirTunesStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fqx_anyplay_service_APController_AirTunesStop
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    AirplayStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_anyplay_service_APController_AirplayStart
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    AirplayStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fqx_anyplay_service_APController_AirplayStop
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    AirTunesPublishService
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fqx_anyplay_service_APController_AirTunesPublishService
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    AirplayPublishService
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fqx_anyplay_service_APController_AirplayPublishService
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    PublishAirTunesService
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fqx_anyplay_service_APController_PublishAirTunesService
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    PublishAirplayService
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fqx_anyplay_service_APController_PublishAirplayService
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    SetAirPlayListener
 * Signature: (Lcom/fqx/anyplay/service/APResultListener;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_SetAirPlayListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    SetAirTunesServerListener
 * Signature: (Lcom/fqx/anyplay/service/APAirTunesServerListener;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_SetAirTunesServerListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    getAirplayPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fqx_anyplay_service_APController_getAirplayPort
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    getSlideshowsPicture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_getSlideshowsPicture
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    mdnsd_start
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fqx_anyplay_service_APController_mdnsd_1start
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    mdnsd_stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fqx_anyplay_service_APController_mdnsd_1stop
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    setNSDRunning
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_setNSDRunning
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
