/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fqx_airjoy_client_MediaAudio */

#ifndef _Included_com_fqx_airjoy_client_MediaAudio
#define _Included_com_fqx_airjoy_client_MediaAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fqx_airjoy_client_MediaAudio
 * Method:    playAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaAudio_playAudio
  (JNIEnv *, jobject, jstring, jstring, jstring, jfloat);

/*
 * Class:     com_fqx_airjoy_client_MediaAudio
 * Method:    setPlayAudioRate
 * Signature: (Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaAudio_setPlayAudioRate
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_fqx_airjoy_client_MediaAudio
 * Method:    stopPlayAudio
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaAudio_stopPlayAudio
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fqx_airjoy_client_MediaAudio
 * Method:    setPlayAudioProgress
 * Signature: (Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaAudio_setPlayAudioProgress
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_fqx_airjoy_client_MediaAudio
 * Method:    getPlayAudioProgress
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaAudio_getPlayAudioProgress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fqx_airjoy_client_MediaAudio
 * Method:    getPlayAudioInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaAudio_getPlayAudioInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
