/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fqx_airjoy_client_MediaPhoto */

#ifndef _Included_com_fqx_airjoy_client_MediaPhoto
#define _Included_com_fqx_airjoy_client_MediaPhoto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fqx_airjoy_client_MediaPhoto
 * Method:    displayPhoto
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaPhoto_displayPhoto
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     com_fqx_airjoy_client_MediaPhoto
 * Method:    displayCachedPhoto
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaPhoto_displayCachedPhoto
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fqx_airjoy_client_MediaPhoto
 * Method:    stopDisplayPhoto
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaPhoto_stopDisplayPhoto
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_airjoy_client_MediaPhoto
 * Method:    rotatePhoto
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaPhoto_rotatePhoto
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_fqx_airjoy_client_MediaPhoto
 * Method:    zoomPhoto
 * Signature: (Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaPhoto_zoomPhoto
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_fqx_airjoy_client_MediaPhoto
 * Method:    movePhoto
 * Signature: (Ljava/lang/String;FF)I
 */
JNIEXPORT jint JNICALL Java_com_fqx_airjoy_client_MediaPhoto_movePhoto
  (JNIEnv *, jobject, jstring, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
