/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fqx_airjoy_server_AirJoy */

#ifndef _Included_com_fqx_airjoy_server_AirJoy
#define _Included_com_fqx_airjoy_server_AirJoy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    setPhotoListener
 * Signature: (Lcom/fqx/airjoy/listener/AirPhotoListener;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_setPhotoListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    setVideoListener
 * Signature: (Lcom/fqx/airjoy/listener/AirVideoListener;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_setVideoListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    setAudioListener
 * Signature: (Lcom/fqx/airjoy/listener/AirAudioListener;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_setAudioListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    setMediaListener
 * Signature: (Lcom/fqx/airjoy/listener/AirMediaListener;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_setMediaListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    setNsdDiscoveryListener
 * Signature: (Lcom/fqx/airjoy/listener/AirJoyNsdDiscoveryListener;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_setNsdDiscoveryListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    setNsdPublishListener
 * Signature: (Lcom/fqx/airjoy/listener/AirJoyNsdPublishListener;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_setNsdPublishListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    clsListenner
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_clsListenner
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    config
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_config
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    ServerStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_ServerStart
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    nsdStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_nsdStart
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    publishService
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_publishService
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    publishMediaEvent
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fqx_airjoy_server_AirJoy_publishMediaEvent
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    native_setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_native_1setup
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_airjoy_server_AirJoy
 * Method:    native_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_airjoy_server_AirJoy_native_1finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
