/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fqx_anyplay_service_APController */

#ifndef _Included_com_fqx_anyplay_service_APController
#define _Included_com_fqx_anyplay_service_APController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    mdnsd_start
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_mdnsd_1start
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    AirplayStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_AirplayStop
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    AirplayStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_AirplayStart
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    PublishEvent
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_PublishEvent
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    getSlideshowsPicture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_getSlideshowsPicture
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    getAirplayPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fqx_anyplay_service_APController_getAirplayPort
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    native_setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_native_1setup
  (JNIEnv *, jobject);

/*
 * Class:     com_fqx_anyplay_service_APController
 * Method:    native_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fqx_anyplay_service_APController_native_1finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
